#!/bin/sh

test x$1 = xstart || exit 0

# Set a path for coredumps that puts them on the persistent filesystem.
# We choose a pattern so that each core dump from a particular binary
# will overwrite the last core dump from that binary -- otherwise we
# could very quickly run out of space.
echo /home/logs/%e.core >/proc/sys/kernel/core_pattern
