#!/bin/sh

test x$1 = xstart || exit 0

if test -e /dev/sda1
then
# Trigger the udev event to mount the USB device and notify printerpanel
udevadm trigger --action=add --subsystem-match=block --property-match=DEVTYPE=partition --property-match=id_type=disk
fi
